name = "EvolvePatterns"
uuid = "db94bb57-a658-4b4f-9c25-e6cab24dceae"
authors = ["Hans Olischläger"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
